### PR TITLE
en_US strings localization

### PR DESCRIPTION
**Pull request by zacyu**

### CODE REVIEW

**Comment by zacyu** [comment]
### Notice

Besides the changes I've made, I highly recommend the `app_name` to be changed to **Pacakage Tracker**. I kept the original name **ExpressHelper** in this commit for the fact that it's the official English name of this project. However, this particular naming can be confusing in English-speaking context. A **shipment** or a **carrier** is generally not referred to as an **express** here, and **Helper** is rarely used in product naming.

**Comment by fython** [comment]
Thanks for noticing. I am sorry that my English skill is too awful to translate strings into English correctly.

In my opinion, this application is developed only for China Mainland. I need some time to consider whether change the "app_name".

**Comment by Harry-Chen** [comment]
其实是whether to...好吧我是打酱油的

发自我的 iPad

在 2015-3-18，13:07，烧饼 notifications@github.com 写道：

**Comment by PeterCxy** [comment]
That's because the Chinese name "水表助手" seems better than "快递追踪", and ExpressHelper is a direct translation.

**Pull request merged**
